[build-system]
requires = [
    "setuptools>=42",
    "wheel", 
    "setuptools_scm[toml]>=6.2"
]
build-backend = "setuptools.build_meta"

# [tool.poetry]
# name = "kosmoss"
# version = "0.1.0"
# description = "Bootcamp"
# license = "MIT"
# authors = ["alxyok <alxyok@naiama.com>"]
# readme = "README.md"
# packages = [{include = "src/kosmoss"}]

# [tool.poetry.dependencies]
# python = "^3.7"
# climetlab = "^0.10"
# climetlab-maelstrom-nogwd = "^0.2"
# climetlab-maelstrom-radiation = "^0.5"
# dask = "2022.02.0"
# eccodes = "2.24.2"
# h5py = "3.6.0"
# HEBO = "0.3.2"
# matplotlib = "3.5.1"
# metaflow = "2.5.2"
# netCDF4 = "1.5.8"
# pandas = "1.3.5"
# plotly = "5.6.0"
# psutil = "5.9.0"
# pylint = "2.12.2"
# pytest = "6.2.5"
# pytorch-lightning = "1.5.9"
# PyYAML = "6.0"
# ray = "1.11.0rc0"
# sklearn = "1.0.2"
# scipy = "1.7.3"
# torch = "1.10.0"
# torch-cluster = "1.5.9"
# 
# importlib-metadata = {version = "^1.0", python = "<3.8"}

# [build-system]
# requires = ["poetry-core"]
# build-backend = "poetry.core.masonry.api"