[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "kosmoss"
version = "0.1.0"
description = "Bootcamp"
license = "MIT"
authors = ["alxyok <alxyok@naiama.com>"]
readme = "README.md"
packages = [{include = "kosmoss", from = "src"}]

[tool.poetry.scripts]
download = "kosmoss.dataproc.download:download"
download_tfrecords = "kosmoss.dataproc.download:download_tfrecords"

[tool.poetry.dependencies]
python = ">3.7.1,<3.11"
climetlab = "0.10.4"
climetlab-maelstrom-nogwd = "0.2.0"
climetlab-maelstrom-radiation = "0.5.4"
cupy-cuda113 = "10.2.0"
dask = "2022.02.0"
eccodes = "1.4.0"
h5py = "3.6.0"
HEBO = "0.3.2"
jupyterlab = "3.2.9"
matplotlib = "3.5.1"
metaflow = "2.5.2"
mpi4py = "3.1.3"
netCDF4 = "1.5.8"
pandas = "1.3.5"
plotly = "5.6.0"
psutil = "5.9.0"
pytorch-lightning = "1.5.10"
PyYAML = "6.0"
ray = "1.11.0rc0"
scikit-learn = "1.0.2"
scipy = "1.7.3"
torch = "1.10.0"
torch-cluster = "1.5.9"
torch-geometric = "2.0.3"
torch-optimizer = "0.3.0"
torch-scatter = "2.0.9"
torch-sparse = "0.6.12"
torch-spline-conv = "1.2.1"
torchmetrics = "0.7.2"
wandb = "0.12.11"

[tool.poetry.dev-dependencies]
pylint = "2.12.2"
pytest = "6.2.5"