fit:
    model:
        class_path: models.LitGAT
        init_args:
            in_channels: 20
            hidden_channels: 8
            out_channels: 4
            num_layers: 4
            dropout: .3
            heads: 8
            lr: .0001

    data:
        class_path: data.LitGNNDataModule
        init_args:
            batch_size: 256
    
    trainer:
        max_epochs: 1
        gpus: 1